"""init

Revision ID: 285dfa458c12
Revises: 
Create Date: 2026-05-27 00:28:02.834294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285dfa458c12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('quartier', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('annonces_dons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('localisation_id', sa.Integer(), nullable=True),
    sa.Column('categorie', sa.String(length=50), nullable=False),
    sa.Column('sous_categorie', sa.String(length=50), nullable=True),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['localisation_id'], ['localisations.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('localisation_id', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('numero_orange_money', sa.String(length=20), nullable=True),
    sa.Column('numero_wave', sa.String(length=20), nullable=True),
    sa.Column('verifie', sa.Boolean(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['localisation_id'], ['localisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missions_volontariat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.Column('localisation_id', sa.Integer(), nullable=True),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('competences_requises', sa.String(length=300), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('places_disponibles', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['localisation_id'], ['localisations.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promesses_dons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('operateur', sa.String(length=30), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions_volontariat.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidatures')
    op.drop_table('promesses_dons')
    op.drop_table('missions_volontariat')
    op.drop_table('structures')
    op.drop_table('annonces_dons')
    op.drop_table('utilisateurs')
    op.drop_table('localisations')
    # ### end Alembic commands ###
